#pragma once

enum MODEL_TYPE { TYPE_NONANIM, TYPE_ANIM, TYPE_END };
enum JOINT_TYPE { JOINT_HINGE, JOINT_BALL, JOINT_END};
enum CONIC_SECTION {SECTION_1, SECTION_2, SECTION_3, SECTION_4 , SECTION_END };