#pragma once

/* For.Status */
#define	STATUS_ZOMBIE_DEFAULT_RECOGNITION_DISTANCE		3.5f		
#define	STATUS_ZOMBIE_MAX_RECOGNITION_DISTANCE			6.f
#define STATUS_ZOMBIE_MAX_RECOGNITION_TIME				5.f
#define STATUS_ZOMBIE_NEED_RECOGNITION_TIME				2.f

#define	STATUS_ZOMBIE_TRY_HOLD_TIME						1.5f
#define	STATUS_ZOMBIE_TRY_HOLD_RANGE					2.f
#define	STATUS_ZOMBIE_BITE_RANGE						1.f

#define	STATUS_ZOMBIE_VIEW_ANGLE						XMConvertToRadians(60.f)
#define STATUS_ZOMBIE_MAX_MOVE_ANGLE					XMConvertToRadians(120.f)

#define	STATUS_ZOMBIE_HEALTH							100.f
#define	STATUS_ZOMBIE_ATTACK							1.f

#define STATUS_ZOMBIE_LIGHTLY_HOLD_RANGE				1.f
#define STATUS_ZOMBIE_TRY_LIGHTLY_HOLD_TIME				0.5f

#define STATUS_ZOMBIE_TRY_STANDUP_TIME					2.f

#define STATUS_ZOMBIE_STAMINA							50.f
#define STATUS_ZOMBIE_STAMINA_MAX						150.f
#define STATUS_ZOMBIE_STAMINA_CHARGING_PER_SEC			3.f

/* For.Use Stamina */
#define ZOMBIE_NEED_STAMINA_BITE						50.f
#define ZOMBIE_NEED_STAMINA_STANDUP						30.f
#define ZOMBIE_NEED_STAMINA_TURN_OVER					20.f


/* For.Zombie Sound */
/* Voice*/
#define ZOMBIE_NUM_SOUND_IDLE_MALE						3		
#define ZOMBIE_NUM_SOUND_IDLE_FEMALE					8		
#define ZOMBIE_NUM_SOUND_IDLE_MALE_BIG					1		//	미설정

#define ZOMBIE_MIN_VOLUME_IDLE							0.3f
#define ZOMBIE_MAX_VOLUME_IDLE							0.5f

#define ZOMBIE_NUM_SOUND_MOVE_MALE						4
#define ZOMBIE_NUM_SOUND_MOVE_FEMALE					6	
#define ZOMBIE_NUM_SOUND_MOVE_MALE_BIG					1		//	미설정

#define ZOMBIE_MIN_VOLUME_MOVE							0.5f
#define ZOMBIE_MAX_VOLUME_MOVE							0.7f

#define ZOMBIE_NUM_SOUND_HOLD_MALE						7
#define ZOMBIE_NUM_SOUND_HOLD_FEMALE					5
#define ZOMBIE_NUM_SOUND_HOLD_MALE_BIG					1		//	미설정

#define ZOMBIE_MIN_VOLUME_HOLD							0.5f
#define ZOMBIE_MAX_VOLUME_HOLD							0.7f

#define ZOMBIE_NUM_SOUND_BITE_MALE						
#define ZOMBIE_NUM_SOUND_BITE_FEMALE						
#define ZOMBIE_NUM_SOUND_BITE_MALE_BIG

#define ZOMBIE_NUM_SOUND_BITE_REJECT_MALE				4			
#define ZOMBIE_NUM_SOUND_BITE_REJECT_FEMALE				1		
#define ZOMBIE_NUM_SOUND_BITE_REJECT_MALE_BIG			1		//	미설정

#define ZOMBIE_MIN_VOLUME_BITE_REJECT					0.5f
#define ZOMBIE_MAX_VOLUME_BITE_REJECT					0.7f

#define ZOMBIE_NUM_SOUND_KNOCKBACK_MALE						
#define ZOMBIE_NUM_SOUND_KNOCKBACK_FEMALE						
#define ZOMBIE_NUM_SOUND_KNOCKBACK_MALE_BIG

/* EF */
#define ZOMBIE_NUM_SOUND_HIT								36
#define ZOMBIE_MIN_VOLUME_HIT								0.3f
#define ZOMBIE_MAX_VOLUME_HIT								0.7f

#define ZOMBIE_VOLUME_BREAK_HEAD							0.6f

/* Interact */
#define ZOMBIE_NUM_SOUND_KNOCK_WINDOW
#define ZOMBIE_NUM_SOUND_BREAK_WINDOW
#define ZOMBIE_NUM_SOUND_KNOCK_DOOR
#define ZOMBIE_NUM_SOUND_OPEN_DOOR

/* Foot */
#define ZOMBIE_NUM_SOUND_FOOT
#define ZOMBIE_MIN_VOLUME_FOOT								0.2f
#define ZOMBIE_MAX_VOLUME_FOOT								0.5f